# Generated by Django 5.0.2 on 2024-02-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteacher',
            old_name='course',
            new_name='course_uuid',
        ),
        migrations.RenameField(
            model_name='courseteacher',
            old_name='teacher',
            new_name='teacher_uuid',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='course',
            new_name='course_uuid',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='group',
            new_name='group_uuid',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='student',
            new_name='student_uuid',
        ),
    ]
