# Generated by Django 5.0.2 on 2024-02-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_course_courseteacher_course_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteacher',
            old_name='course_uuid',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='courseteacher',
            old_name='teacher_uuid',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='course_uuid',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='group_uuid',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='student_uuid',
            new_name='student',
        ),
    ]
