# Generated by Django 5.0.2 on 2024-02-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_uuid_courseteacher_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='uuid',
            new_name='course_uuid',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='uuid',
            new_name='group_uuid',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='uuid',
            new_name='lesson_uuid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='uuid',
            new_name='student_uuid',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='uuid',
            new_name='teacher_uuid',
        ),
    ]
