# Generated by Django 5.0.2 on 2024-02-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'course',
            '0005_alter_course_course_uuid_alter_group_group_uuid_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(
                through='course.StudentGroup', to='course.student'
            ),
        ),
    ]
